[package]
name = "x11-input-supercharger"
version = "0.2.2"
description = "Adds system-wide Windows-like scrolling mode and conditional clicking using keyboard"
authors = ["Paweł Zmarzły <pawo2500@gmail.com>"]
repository = "https://github.com/pzmarzly/x11-input-supercharger"
keywords = ["x11", "mouse", "keyboard", "xserver", "tablet"]
readme = "README.md"
categories = ["command-line-utilities"]
license = "MIT"

[dependencies]
serde = "1.0.71"
serde_derive = "1.0.71"
toml = "0.4.6"
lazy-panic = "0.3.2"
ctrlc = "3.1.1"

[profile.release]
lto = true